# ==========================================================================
# 1. PORTO E ESTRATÉGIA DE SERVIDOR (PRODUÇÃO / NUVEM)
# ==========================================================================
server.port=${PORT:8080}

# 🚀 CORREÇÃO DO OAUTH2: Avisa ao Spring para usar o domínio real da Render (HTTPS) 
# em vez de gerar 'localhost:8080' na URI de redirecionamento enviada ao Google.
server.forward-headers-strategy=FRAMEWORK


# ==========================================================================
# 2. CONFIGURAÇÕES DO APLICATIVO E BANCO DE DADOS H2
# ==========================================================================
spring.application.name=backend

# Configuração do Banco de Dados H2 em Memória
spring.datasource.url=jdbc:h2:mem:ilsegretodb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Ativando o Painel de Controle do Banco de Dados (H2 Console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Configuração do JPA / Hibernate para criar as tabelas automaticamente
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# ==========================================================================
# 3. SEGURANÇA E LOGIN SOCIAL (GOOGLE OAUTH2)
# ==========================================================================
spring.security.oauth2.client.registration.google.client-id=337781717721-fidih7cvr57947qfi6vdkpuk4e286bc1.apps.googleusercontent.com

# O Spring vai tentar buscar uma variável de ambiente na Render/Windows, se não achar, usa a sua chave padrão:
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET: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}
spring.security.oauth2.client.registration.google.scope=email,profile